examples/cpp03: fix build without std::chrono
* e.g. with ubuntu 16.04  __GXX_EXPERIMENTAL_CXX0X__ isn't enabled by
  default in g++ 5.4.0 and default __cplusplus 199711L, because of
  that ASIO_HAS_STD_CHRONO doesn't get defined and even when
  ASIO_HAS_BOOST_CHRONO is defined later, it doesn't add boost_chrono
  library when linking the icmp and timeouts examples, which results
  in that linking failure for timeouts/blocking_token_tcp_client:

g++  -I../../../../asio-1.12.1/src/examples/cpp03/../../../include -isystem/OE/ros1-melodic-thud/tmp-glibc/work/x86_64-linux/asio-native/1.12.1-r0/recipe-sysroot-native/usr/include -O2 -pipe -pthread -ftemplate-depth-256  -L/OE/ros1-melodic-thud/tmp-glibc/work/x86_64-linux/asio-native/1.12.1-r0/recipe-sysroot-native/usr/lib -L/OE/ros1-melodic-thud/tmp-glibc/work/x86_64-linux/asio-native/1.12.1-r0/recipe-sysroot-native/lib -Wl,-rpath-link,/OE/ros1-melodic-thud/tmp-glibc/work/x86_64-linux/asio-native/1.12.1-r0/recipe-sysroot-native/usr/lib -Wl,-rpath-link,/OE/ros1-melodic-thud/tmp-glibc/work/x86_64-linux/asio-native/1.12.1-r0/recipe-sysroot-native/lib -Wl,-rpath,/OE/ros1-melodic-thud/tmp-glibc/work/x86_64-linux/asio-native/1.12.1-r0/recipe-sysroot-native/usr/lib -Wl,-rpath,/OE/ros1-melodic-thud/tmp-glibc/work/x86_64-linux/asio-native/1.12.1-r0/recipe-sysroot-native/lib -Wl,-O1 -Wl,--allow-shlib-undefined -Wl,--dynamic-linker=/OE/ros1-melodic-thud/tmp-glibc/sysroots-uninative/x86_64-linux/lib/ld-linux-x86-64.so.2 -pthread -o timeouts/blocking_token_tcp_client timeouts/blocking_token_tcp_client.o  -lssl -lcrypto -lrt
timeouts/blocking_token_tcp_client.o: In function `unsigned long asio::io_context::run_one_until<boost::chrono::steady_clock, boost::chrono::duration<long, boost::ratio<1l, 1000000000l> > >(boost::chrono::time_point<boost::chrono::steady_clock, boost::chrono::duration<long, boost::ratio<1l, 1000000000l> > > const&)':
blocking_token_tcp_client.cpp:(.text._ZN4asio10io_context13run_one_untilIN5boost6chrono12steady_clockENS3_8durationIlNS2_5ratioILl1ELl1000000000EEEEEEEmRKNS3_10time_pointIT_T0_EE[_ZN4asio10io_context13run_one_untilIN5boost6chrono12steady_clockENS3_8durationIlNS2_5ratioILl1ELl1000000000EEEEEEEmRKNS3_10time_pointIT_T0_EE]+0x2b): undefined reference to `boost::chrono::steady_clock::now()'
blocking_token_tcp_client.cpp:(.text._ZN4asio10io_context13run_one_untilIN5boost6chrono12steady_clockENS3_8durationIlNS2_5ratioILl1ELl1000000000EEEEEEEmRKNS3_10time_pointIT_T0_EE[_ZN4asio10io_context13run_one_untilIN5boost6chrono12steady_clockENS3_8durationIlNS2_5ratioILl1ELl1000000000EEEEEEEmRKNS3_10time_pointIT_T0_EE]+0x4d1): undefined reference to `boost::chrono::steady_clock::now()'
timeouts/blocking_token_tcp_client.o: In function `unsigned long asio::io_context::run_for<long, boost::ratio<1l, 1000000000l> >(boost::chrono::duration<long, boost::ratio<1l, 1000000000l> > const&)':
blocking_token_tcp_client.cpp:(.text._ZN4asio10io_context7run_forIlN5boost5ratioILl1ELl1000000000EEEEEmRKNS2_6chrono8durationIT_T0_EE[_ZN4asio10io_context7run_forIlN5boost5ratioILl1ELl1000000000EEEEEmRKNS2_6chrono8durationIT_T0_EE]+0x1d): undefined reference to `boost::chrono::steady_clock::now()'
timeouts/blocking_token_tcp_client.o: In function `main':
blocking_token_tcp_client.cpp:(.text.startup+0x41c): undefined reference to `boost::chrono::steady_clock::now()'
blocking_token_tcp_client.cpp:(.text.startup+0xb5d): undefined reference to `boost::chrono::steady_clock::now()'
collect2: error: ld returned 1 exit status

  and similarly for icmp/ping:

g++  -I../../../../asio-1.12.1/src/examples/cpp03/../../../include -isystem/OE/ros1-melodic-thud/tmp-glibc/work/x86_64-linux/asio-native/1.12.1-r0/recipe-sysroot-native/usr/include -O2 -pipe -pthread -ftemplate-depth-256  -L/OE/ros1-melodic-thud/tmp-glibc/work/x86_64-linux/asio-native/1.12.1-r0/recipe-sysroot-native/usr/lib -L/OE/ros1-melodic-thud/tmp-glibc/work/x86_64-linux/asio-native/1.12.1-r0/recipe-sysroot-native/lib -Wl,-rpath-link,/OE/ros1-melodic-thud/tmp-glibc/work/x86_64-linux/asio-native/1.12.1-r0/recipe-sysroot-native/usr/lib -Wl,-rpath-link,/OE/ros1-melodic-thud/tmp-glibc/work/x86_64-linux/asio-native/1.12.1-r0/recipe-sysroot-native/lib -Wl,-rpath,/OE/ros1-melodic-thud/tmp-glibc/work/x86_64-linux/asio-native/1.12.1-r0/recipe-sysroot-native/usr/lib -Wl,-rpath,/OE/ros1-melodic-thud/tmp-glibc/work/x86_64-linux/asio-native/1.12.1-r0/recipe-sysroot-native/lib -Wl,-O1 -Wl,--allow-shlib-undefined -Wl,--dynamic-linker=/OE/ros1-melodic-thud/tmp-glibc/sysroots-uninative/x86_64-linux/lib/ld-linux-x86-64.so.2 -pthread -o icmp/ping icmp/ping.o  -lssl -lcrypto -lrt
icmp/ping.o: In function `asio::detail::timer_queue<asio::detail::chrono_time_traits<boost::chrono::steady_clock, asio::wait_traits<boost::chrono::steady_clock> > >::wait_duration_msec(long) const':
ping.cpp:(.text._ZNK4asio6detail11timer_queueINS0_18chrono_time_traitsIN5boost6chrono12steady_clockENS_11wait_traitsIS5_EEEEE18wait_duration_msecEl[_ZNK4asio6detail11timer_queueINS0_18chrono_time_traitsIN5boost6chrono12steady_clockENS_11wait_traitsIS5_EEEEE18wait_duration_msecEl]+0x1b): undefined reference to `boost::chrono::steady_clock::now()'
icmp/ping.o: In function `asio::detail::timer_queue<asio::detail::chrono_time_traits<boost::chrono::steady_clock, asio::wait_traits<boost::chrono::steady_clock> > >::wait_duration_usec(long) const':
ping.cpp:(.text._ZNK4asio6detail11timer_queueINS0_18chrono_time_traitsIN5boost6chrono12steady_clockENS_11wait_traitsIS5_EEEEE18wait_duration_usecEl[_ZNK4asio6detail11timer_queueINS0_18chrono_time_traitsIN5boost6chrono12steady_clockENS_11wait_traitsIS5_EEEEE18wait_duration_usecEl]+0x1b): undefined reference to `boost::chrono::steady_clock::now()'
icmp/ping.o: In function `asio::detail::timer_queue<asio::detail::chrono_time_traits<boost::chrono::steady_clock, asio::wait_traits<boost::chrono::steady_clock> > >::get_ready_timers(asio::detail::op_queue<asio::detail::scheduler_operation>&)':
ping.cpp:(.text._ZN4asio6detail11timer_queueINS0_18chrono_time_traitsIN5boost6chrono12steady_clockENS_11wait_traitsIS5_EEEEE16get_ready_timersERNS0_8op_queueINS0_19scheduler_operationEEE[_ZN4asio6detail11timer_queueINS0_18chrono_time_traitsIN5boost6chrono12steady_clockENS_11wait_traitsIS5_EEEEE16get_ready_timersERNS0_8op_queueINS0_19scheduler_operationEEE]+0x33): undefined reference to `boost::chrono::steady_clock::now()'
icmp/ping.o: In function `pinger::handle_receive(unsigned long)':
ping.cpp:(.text._ZN6pinger14handle_receiveEm[_ZN6pinger14handle_receiveEm]+0x4d8): undefined reference to `boost::chrono::steady_clock::now()'
icmp/ping.o: In function `pinger::start_send()':
ping.cpp:(.text._ZN6pinger10start_sendEv[_ZN6pinger10start_sendEv]+0x307): undefined reference to `boost::chrono::steady_clock::now()'
collect2: error: ld returned 1 exit status
Makefile:1349: recipe for target 'icmp/ping' failed
make: *** [icmp/ping] Error 1

Signed-off-by: Martin Jansa <martin.jansa@lge.com>