Compile fix for Visual C++ 2013 Update 3
Starting with Visual C++ Update 3 RC, WSAAddressToStringA is deprecated.
This leads to a compiler warning which is treated as an error with the /sdl switch (which is enabled by default for new projects):
error C4996: 'WSAAddressToStringA': Use WSAAddressToStringW() instead or define _WINSOCK_DEPRECATED_NO_WARNINGS to disable deprecated API warnings
This change calls WSAAddressToStringW instead of WSAAddressToStringA for Visual C++ 2013 and later.